export const enum LanguageCode {
  AFRIKAANS = "af",
  ALBANIAN = "al",
  ARABIC = "ar",
  AZERBAIJANI = "az",
  BULGARIAN = "bg",
  CATALAN = "ca",
  CZECH = "cz",
  DANISH = "da",
  GERMAN = "de",
  GREEK = "el",
  ENGLISH = "en",
  BASQUE = "eu",
  /** also Farsi */
  PERSIAN = "fa",
  FINNISH = "fi",
  FRENCH = "fr",
  GALICIAN = "gl",
  HEBREW = "he",
  HINDI = "hi",
  CROATIAN = "hr",
  HUNGARIAN = "hu",
  INDONESIAN = "id",
  ITALIAN = "it",
  JAPANESE = "ja",
  KOREAN = "kr",
  LATVIAN = "la",
  LITHUANIAN = "lt",
  MACEDONIAN = "mk",
  NORWEGIAN = "no",
  DUTCH = "nl",
  POLISH = "pl",
  PORTUGUESE = "pt",
  PORTUGUESE_BRASIL = "pt_br",
  ROMANIAN = "ro",
  RUSSIAN = "ru",
  /** value also could be `se` */
  SWEDISH = "sv",
  SLOVAK = "sk",
  SLOVENIAN = "sl",
  /** value also could be `es` */
  SPANISH = "sp",
  SERBIAN = "sr",
  THAI = "th",
  TURKISH = "tr",
  /** value also could be `uk` */
  UKRAINIAN = "ua",
  VIETNAMESE = "vi",
  CHINESE_SIMPLIFIED = "zh_cn",
  CHINESE_TRADITIONAL = "zh_tw",
  ZULU = "zu"
};
